source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Umbala-Interview-Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Umbala-Interview-Test
  pod 'Alamofire', '~> 4.7'
  pod 'SnapKit', '~> 4.0'

end